### PR TITLE
Added synergy effect

### PR DESCRIPTION
**Pull request by Br1ckst0n**
I've added the synergy effect/description to the embellishTechniques method, as I would like to have this property. I have run the data command and it did successfully retrieve the synergy effects.

I also noticed that the effectText property was missing from the interface, so i added that.

### CODE REVIEW

**Comment by JanVogelsang** [comment]
Neat! @maael What do you think, can this get merged? I need the synergy effect information as well.

**Comment by maael** [comment]
👋 Hey - before this can be merged, @Br1ckst0n needs to add the new fields to https://github.com/maael/temtem-api/blob/master/scripts/checker/codecs/techniques.ts#L23, otherwise it'll be marked as a failed update.

The produced data from `yarn data techniques` should be committed for review too.

Once both of those changes are done, and I've reviewed it, I can get it merged. 👍 

I need to add those requirements on to a PR template at some point.

**Comment by Br1ckst0n** [comment]
I did add the prop to the ts class and updated the data file

**Comment by maael** [comment]
Heya, thanks for the contribution! That's merged now, and the synergy effects will be available soon!

**Pull request merged**
